name: Build & Test Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Sayu
        run: cd Sayu && ./gradlew clean build

      - name: Build Algoexpert
        run: cd Algoexpert && ./gradlew clean build